export const GET_MARKET_DATA = 'GET_MARKET_DATA';
export const GET_MYCARDS_DATA = 'GET_MYCARDS_DATA';
export const GET_BUDGET_DATA = 'GET_BUDGET_DATA';
export const GET_PLAYER_DETAILS_DATA = 'GET_PLAYER_DETAILS_DATA';
export const UPDATE_BUDGET = 'UPDATE_BUDGET';
export const BUY_CARD = 'BUY_CARD';
export const SELL_CARD = 'SELL_CARD';
export const SORT_MARKET_DATA = 'SORT_MARKET_DATA';
export const FILTER_MARKET_DATA = 'FILTER_MARKET_DATA';
export const FILTER_MYCARDS_DATA = 'FILTER_MYCARDS_DATA';

