export const OPEN_TRADE_MODAL = 'OPEN_TRADE_MODAL';
export const OPEN_PLAYER_DETAILS_MODAL = 'OPEN_PLAYER_DETAILS_MODAL';
export const OPEN_NOT_ENOUGHT_MONEY_MODAL = 'OPEN_NOT_ENOUGHT_MONEY_MODAL';
export const CLOSE_TRADE_MODAL = 'CLOSE_TRADE_MODAL';
export const CLOSE_PLAYER_DETAILS_MODAL = 'CLOSE_PLAYER_DETAILS_MODAL';
export const CLOSE_NOT_ENOUGHT_MONEY_MODAL = 'CLOSE_NOT_ENOUGHT_MONEY_MODAL';